import { execFile } from "node:child_process";
import { mkdir, readFile, symlink, unlink, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { join } from "node:path";
import { promisify } from "node:util";
import { themeSchema, type StudioTheme } from "../shared/theme";
import { RevisionConflict, StudioStore } from "./store";
import { exportAssets } from "./export-assets";

const exec = promisify(execFile);
const shellQuote = (value: string) => "'" + value.replaceAll("'", "'\\''") + "'";

function entry(): string {
  return `import type { PluginClientContext, PluginSurfaceProps, PluginWorkspacePanelProps } from "@getpaseo/plugin/client";
import { ScrollView, Text, View } from "react-native";
import { RecipePanel, PackActivity, registerPackExtensions } from "./client/pack-runtime";
import { pack } from "./client/pack";
export default function contribute(client: PluginClientContext) {
  client.addTheme({ id: "pack", name: pack.name, appearance: pack.appearance, colors: pack.colors });
  const cleanup = registerPackExtensions(client, () => pack);
  function Overview({ theme }: PluginSurfaceProps) {
    return <ScrollView style={{flex:1,backgroundColor:theme.colors.surface0}} contentContainerStyle={{padding:24,gap:16}}>
      <Text style={{color:theme.colors.foreground,fontSize:20,fontWeight:"600"}}>{pack.name}</Text>
      <Text style={{color:theme.colors.foregroundMuted,fontSize:13,lineHeight:20}}>Select this pack in Settings → Appearance for its palette. Its registered extensions style completed text tools and its own panels. Native Paseo fonts and layout stay in your app settings.</Text>
      <RecipePanel theme={theme} pack={pack}/>
    </ScrollView>;
  }
  client.addSurface("overview", Overview);
  client.addSidebarItem({id:"overview",title:pack.name,icon:"Palette",surface:"overview"});
  if (pack.ui.activityPanel || pack.ui.panel.enabled) {
    function Panel(props: PluginWorkspacePanelProps) {return <PackActivity theme={props.theme} workspaceId={props.workspaceId} pack={pack}/>;}
    client.addWorkspacePanel({id:"design-panel",title:pack.ui.panel.enabled ? pack.ui.panel.title : "Pack activity",icon:pack.ui.panel.enabled ? pack.ui.panel.icon : "Activity",context:"workspace",locations:["workspace","explorer"],Component:Panel});
    client.addCommandCenterItem({id:"open-panel",title:"Open " + (pack.ui.panel.enabled ? pack.ui.panel.title : "Pack activity"),icon:"PanelsTopLeft",context:"workspace",onSelect({openPanel}) {openPanel("design-panel",{location:"explorer"});}});
  }
  return cleanup;
}
`;
}

export class PackExporter {
  constructor(private readonly store: StudioStore) {}
  async export(input: { expectedRevision: number; name?: string }) {
    const document = await this.store.read();
    if (document.revision !== input.expectedRevision) throw new RevisionConflict(document.revision);
    const pack: StudioTheme = themeSchema.parse({ ...document.current, ...(input.name ? { name: input.name } : {}) });
    const slug =
      pack.name
        .toLowerCase()
        .normalize("NFKD")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")
        .slice(0, 38) || "design";
    const id = "theme-pack-" + slug;
    const directory = join(this.store.directory, "exports", id + "-" + randomUUID().slice(0, 8));
    await mkdir(directory, { recursive: true, mode: 0o700 });
    const tooling = JSON.parse(await readFile(join(exportAssets.projectDirectory, "package.json"), "utf8"));
    const files: Record<string, string> = {
      ...exportAssets.files,
      "index.client.tsx": entry(),
      "client/pack.ts":
        'import type { StudioTheme } from "../shared/theme";\nexport const pack: StudioTheme = ' +
        JSON.stringify(pack, null, 2) +
        ";\n",
      "paseo-plugin.json":
        JSON.stringify(
          {
            id,
            description: "Design pack generated by Theme Studio: " + pack.name,
            requirements: { paseo: ">=0.9.2 <0.11.0" },
          },
          null,
          2,
        ) + "\n",
      "package.json":
        JSON.stringify(
          {
            name: id,
            version: "1.0.0",
            private: true,
            license: "Apache-2.0",
            files: [
              "paseo-plugin.json",
              "index.client.tsx",
              "client/",
              "shared/",
              "pack.json",
              "README.md",
              "LICENSE",
              "NOTICE",
            ],
            scripts: { typecheck: "tsc --noEmit" },
            devDependencies: Object.fromEntries(
              Object.entries(tooling.devDependencies).filter(
                ([name]) => !["playwright", "tsx", "@types/node"].includes(name),
              ),
            ),
          },
          null,
          2,
        ) + "\n",
      "tsconfig.json":
        JSON.stringify(
          {
            compilerOptions: {
              target: "ES2020",
              module: "ESNext",
              moduleResolution: "Bundler",
              lib: ["ES2023"],
              types: ["react"],
              jsx: "react-jsx",
              strict: true,
              skipLibCheck: true,
              noEmit: true,
              esModuleInterop: true,
            },
            include: ["index.client.tsx", "client/**/*.ts", "client/**/*.tsx", "shared/**/*.ts"],
          },
          null,
          2,
        ) + "\n",
      "pack.json": JSON.stringify(pack, null, 2) + "\n",
      "README.md": `# ${pack.name}\n\nAn independent Paseo design pack exported from Theme Studio at document revision ${document.revision}. Requires Paseo 0.9.2–0.10.x.\n\nInstall this directory with Paseo's Plugins UI or the CLI. Choose ${pack.name} in Settings → Appearance for the palette. Open the workspace design panel from the Command Center when enabled. The pack's typography, spacing and radii apply to its components, not to the native application layout.\n\nThe source is generated from a fixed native renderer and validated declarative data. No credentials, agent conversations, bridge tokens or Theme Studio state are included.\n\nRun pnpm install and pnpm typecheck to check it independently. Disable or remove the plugin from Settings → Plugins to remove its extensions.\n`,
      LICENSE: await readFile(join(exportAssets.projectDirectory, "LICENSE"), "utf8"),
      NOTICE:
        "Generated by Paseo Theme Studio. Native renderer adapted from Paseo's public theme and plugin contracts. Licensed under Apache 2.0.\nhttps://github.com/getpaseo/paseo\n",
    };
    for (const [name, contents] of Object.entries(files)) {
      const target = join(directory, name);
      await mkdir(join(target, ".."), { recursive: true, mode: 0o700 });
      await writeFile(target, contents, { mode: 0o600 });
    }
    const modules = join(directory, "node_modules");
    await symlink(join(exportAssets.projectDirectory, "node_modules"), modules, "dir");
    try {
      await exec(
        process.execPath,
        [
          join(exportAssets.projectDirectory, "node_modules/typescript/lib/tsc.js"),
          "--project",
          join(directory, "tsconfig.json"),
          "--noEmit",
        ],
        { timeout: 30000, maxBuffer: 1000000 },
      );
    } catch (error) {
      const failure = error as Error & { stdout?: string; stderr?: string };
      throw new Error(
        `The pack did not pass typechecking and has not been installed. Sources are preserved at ${directory}. ${(failure.stdout || failure.stderr || failure.message).slice(0, 1600)}`,
      );
    } finally {
      await unlink(modules);
    }
    await writeFile(
      join(directory, "validation.json"),
      JSON.stringify(
        { typecheck: true, sourceRevision: document.revision, generatedAt: new Date().toISOString() },
        null,
        2,
      ) + "\n",
      { mode: 0o600 },
    );
    return {
      directory,
      files: [...Object.keys(files), "validation.json"],
      validation: { typecheck: true },
      installCommand: "paseo plugin install " + shellQuote(directory),
    };
  }
}
