// Generated by scripts/import-t3-themes.mjs from https://github.com/SunkenInTime/t3-themes
// at e3022c7b8db85eadb3bbdf412be4fc2eab93ca58. Do not edit by hand; rerun the script instead.
// Each palette is adapted from a community theme for T3 Code and credited to its author.
import type { Palette } from "./theme";

export type CommunityPreset = {
  id: string;
  name: string;
  appearance: "light" | "dark";
  author: string;
  source: string;
  colors: Palette;
};

export const communityPresets: CommunityPreset[] = [
  {
    "id": "t3-apple-frost-light",
    "name": "Apple Frost Light",
    "appearance": "light",
    "author": "saltjsx",
    "source": "https://t3themes.com/themes/apple-frost/",
    "colors": {
      "background": "#F5F5F7",
      "foreground": "#1D1D1F",
      "raised": "#F4F8FB",
      "control": "#E2E2E5",
      "border": "#D2D2D7",
      "accent": "#0071E3",
      "mutedForeground": "#6E6E73",
      "ring": "#0071E3"
    }
  },
  {
    "id": "t3-apple-frost-dark",
    "name": "Apple Frost Dark",
    "appearance": "dark",
    "author": "saltjsx",
    "source": "https://t3themes.com/themes/apple-frost/",
    "colors": {
      "background": "#000000",
      "foreground": "#F5F5F7",
      "raised": "#252527",
      "control": "#2C2C2E",
      "border": "#333333",
      "accent": "#0A84FF",
      "mutedForeground": "#8E8E93",
      "ring": "#0A84FF"
    }
  },
  {
    "id": "t3-aura",
    "name": "Aura",
    "appearance": "dark",
    "author": "inovvia",
    "source": "https://t3themes.com/themes/aura/",
    "colors": {
      "background": "#15141B",
      "foreground": "#EDECEE",
      "raised": "#211D26",
      "control": "#29263C",
      "border": "#3B334B",
      "accent": "#A277FF",
      "mutedForeground": "#ADACAE",
      "ring": "#A277FF"
    }
  },
  {
    "id": "t3-catppuccin-frappe-light",
    "name": "Catppuccin Frappé Light",
    "appearance": "light",
    "author": "jainvaibhav671",
    "source": "https://t3themes.com/themes/catppuccin-frappe/",
    "colors": {
      "background": "#EFF1F5",
      "foreground": "#4C4F69",
      "raised": "#CCD0DA",
      "control": "#DCE0E8",
      "border": "#CCD0DA",
      "accent": "#8839EF",
      "mutedForeground": "#6C6F85",
      "ring": "#8839EF"
    }
  },
  {
    "id": "t3-catppuccin-frappe-dark",
    "name": "Catppuccin Frappé Dark",
    "appearance": "dark",
    "author": "jainvaibhav671",
    "source": "https://t3themes.com/themes/catppuccin-frappe/",
    "colors": {
      "background": "#303446",
      "foreground": "#C6D0F5",
      "raised": "#414559",
      "control": "#414559",
      "border": "#51576D",
      "accent": "#CA9EE6",
      "mutedForeground": "#A5ADCE",
      "ring": "#CA9EE6"
    }
  },
  {
    "id": "t3-catppuccin-macchiato-light",
    "name": "Catppuccin Macchiato Light",
    "appearance": "light",
    "author": "jainvaibhav671",
    "source": "https://t3themes.com/themes/catppuccin-macchiato/",
    "colors": {
      "background": "#EFF1F5",
      "foreground": "#4C4F69",
      "raised": "#CCD0DA",
      "control": "#DCE0E8",
      "border": "#CCD0DA",
      "accent": "#8839EF",
      "mutedForeground": "#6C6F85",
      "ring": "#8839EF"
    }
  },
  {
    "id": "t3-catppuccin-macchiato-dark",
    "name": "Catppuccin Macchiato Dark",
    "appearance": "dark",
    "author": "jainvaibhav671",
    "source": "https://t3themes.com/themes/catppuccin-macchiato/",
    "colors": {
      "background": "#24273A",
      "foreground": "#CAD3F5",
      "raised": "#363A4F",
      "control": "#363A4F",
      "border": "#494D64",
      "accent": "#C6A0F6",
      "mutedForeground": "#A5ADCB",
      "ring": "#C6A0F6"
    }
  },
  {
    "id": "t3-catppuccin-mocha-light",
    "name": "Catppuccin Mocha Light",
    "appearance": "light",
    "author": "jainvaibhav671",
    "source": "https://t3themes.com/themes/catppuccin-mocha/",
    "colors": {
      "background": "#EFF1F5",
      "foreground": "#4C4F69",
      "raised": "#CCD0DA",
      "control": "#DCE0E8",
      "border": "#CCD0DA",
      "accent": "#8839EF",
      "mutedForeground": "#6C6F85",
      "ring": "#8839EF"
    }
  },
  {
    "id": "t3-catppuccin-mocha-dark",
    "name": "Catppuccin Mocha Dark",
    "appearance": "dark",
    "author": "jainvaibhav671",
    "source": "https://t3themes.com/themes/catppuccin-mocha/",
    "colors": {
      "background": "#1E1E2E",
      "foreground": "#CDD6F4",
      "raised": "#313244",
      "control": "#313244",
      "border": "#45475A",
      "accent": "#CBA6F7",
      "mutedForeground": "#A6ADC8",
      "ring": "#CBA6F7"
    }
  },
  {
    "id": "t3-cherry-noir",
    "name": "Cherry Noir",
    "appearance": "dark",
    "author": "emmsixx",
    "source": "https://t3themes.com/themes/cherry-noir/",
    "colors": {
      "background": "#0D0A0C",
      "foreground": "#E9DEE2",
      "raised": "#20141A",
      "control": "#211319",
      "border": "#2A1A20",
      "accent": "#D21F50",
      "mutedForeground": "#AD909B",
      "ring": "#D21F50"
    }
  },
  {
    "id": "t3-claude-dark",
    "name": "Claude Dark",
    "appearance": "dark",
    "author": "timvdhoorn",
    "source": "https://t3themes.com/themes/claude/",
    "colors": {
      "background": "#151515",
      "foreground": "#F9F9F7",
      "raised": "#20201F",
      "control": "#20201F",
      "border": "#2D2D2D",
      "accent": "#D97757",
      "mutedForeground": "#898781",
      "ring": "#D97757"
    }
  },
  {
    "id": "t3-claude-light",
    "name": "Claude Light",
    "appearance": "light",
    "author": "timvdhoorn",
    "source": "https://t3themes.com/themes/claude/",
    "colors": {
      "background": "#FCFCFB",
      "foreground": "#131313",
      "raised": "#FFFFFF",
      "control": "#FFFFFF",
      "border": "#E3E3E2",
      "accent": "#D97757",
      "mutedForeground": "#898781",
      "ring": "#C6613F"
    }
  },
  {
    "id": "t3-dracula-pycharm",
    "name": "Dracula PyCharm",
    "appearance": "dark",
    "author": "YanivZalach",
    "source": "https://t3themes.com/themes/dracula-pycharm/",
    "colors": {
      "background": "#171717",
      "foreground": "#F0F4F8",
      "raised": "#2B2B2B",
      "control": "#3C3F41",
      "border": "#505050",
      "accent": "#4FB3FF",
      "mutedForeground": "#A3ADB6",
      "ring": "#4FB3FF"
    }
  },
  {
    "id": "t3-dracula",
    "name": "Dracula",
    "appearance": "dark",
    "author": "itriibouanane",
    "source": "https://t3themes.com/themes/dracula/",
    "colors": {
      "background": "#282A36",
      "foreground": "#F8F8F2",
      "raised": "#2B2D3A",
      "control": "#343746",
      "border": "#44475A",
      "accent": "#BD93F9",
      "mutedForeground": "#6272A4",
      "ring": "#BD93F9"
    }
  },
  {
    "id": "t3-espresso-dark",
    "name": "Espresso Dark",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/espresso/",
    "colors": {
      "background": "#241C17",
      "foreground": "#E8DCD0",
      "raised": "#332921",
      "control": "#372C24",
      "border": "#3C3129",
      "accent": "#C58D5F",
      "mutedForeground": "#B3A191",
      "ring": "#C58D5F"
    }
  },
  {
    "id": "t3-espresso-light",
    "name": "Espresso Light",
    "appearance": "light",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/espresso/",
    "colors": {
      "background": "#F3EDE4",
      "foreground": "#3B2F2A",
      "raised": "#F8F3EA",
      "control": "#E5DACB",
      "border": "#DDD2C2",
      "accent": "#8C5A3C",
      "mutedForeground": "#7C6A5D",
      "ring": "#8C5A3C"
    }
  },
  {
    "id": "t3-fjord-light",
    "name": "Fjord Light",
    "appearance": "light",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/fjord/",
    "colors": {
      "background": "#ECEFF4",
      "foreground": "#2E3440",
      "raised": "#F2F4F8",
      "control": "#DDE3EC",
      "border": "#D8DEE9",
      "accent": "#5E81AC",
      "mutedForeground": "#5E6A7E",
      "ring": "#5E81AC"
    }
  },
  {
    "id": "t3-fjord-dark",
    "name": "Fjord Dark",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/fjord/",
    "colors": {
      "background": "#2E3440",
      "foreground": "#ECEFF4",
      "raised": "#3B4252",
      "control": "#3B4252",
      "border": "#434C5E",
      "accent": "#88C0D0",
      "mutedForeground": "#A3AEC2",
      "ring": "#88C0D0"
    }
  },
  {
    "id": "t3-harbor-bronze-dark",
    "name": "Harbor Bronze Dark",
    "appearance": "dark",
    "author": "kototok903",
    "source": "https://t3themes.com/themes/harbor-bronze/",
    "colors": {
      "background": "#0A1318",
      "foreground": "#CED1CE",
      "raised": "#111B20",
      "control": "#151F24",
      "border": "#263239",
      "accent": "#5B91A2",
      "mutedForeground": "#737E83",
      "ring": "#5B91A2"
    }
  },
  {
    "id": "t3-harbor-bronze-light",
    "name": "Harbor Bronze Light",
    "appearance": "light",
    "author": "kototok903",
    "source": "https://t3themes.com/themes/harbor-bronze/",
    "colors": {
      "background": "#EDF1F0",
      "foreground": "#283235",
      "raised": "#F2F5F4",
      "control": "#EDF1F0",
      "border": "#CBD4D4",
      "accent": "#47798A",
      "mutedForeground": "#687579",
      "ring": "#47798A"
    }
  },
  {
    "id": "t3-kanagawa-dark",
    "name": "Kanagawa Dark",
    "appearance": "dark",
    "author": "njpatel",
    "source": "https://t3themes.com/themes/kanagawa/",
    "colors": {
      "background": "#1F1F28",
      "foreground": "#DCD7BA",
      "raised": "#2A2A37",
      "control": "#2A2A37",
      "border": "#363646",
      "accent": "#DCD7BA",
      "mutedForeground": "#727169",
      "ring": "#DCD7BA"
    }
  },
  {
    "id": "t3-kanagawa-light",
    "name": "Kanagawa Light",
    "appearance": "light",
    "author": "njpatel",
    "source": "https://t3themes.com/themes/kanagawa/",
    "colors": {
      "background": "#F2EEDD",
      "foreground": "#545464",
      "raised": "#FAF8EC",
      "control": "#E0D9BD",
      "border": "#D4CDAE",
      "accent": "#545464",
      "mutedForeground": "#7D7A6F",
      "ring": "#545464"
    }
  },
  {
    "id": "t3-miami-nights",
    "name": "Miami Nights",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/miami-nights/",
    "colors": {
      "background": "#17102B",
      "foreground": "#F3E9FF",
      "raised": "#241A44",
      "control": "#2A1D4D",
      "border": "#2C2050",
      "accent": "#FF5FA2",
      "mutedForeground": "#A78FC9",
      "ring": "#3BE8F0"
    }
  },
  {
    "id": "t3-midnight-harbor",
    "name": "Midnight Harbor",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/midnight-harbor/",
    "colors": {
      "background": "#0B0E14",
      "foreground": "#D6DCE6",
      "raised": "#1A2029",
      "control": "#1F2631",
      "border": "#232A36",
      "accent": "#7AA2F7",
      "mutedForeground": "#8A94A6",
      "ring": "#7AA2F7"
    }
  },
  {
    "id": "t3-nectar",
    "name": "Nectar",
    "appearance": "dark",
    "author": "glarivie",
    "source": "https://t3themes.com/themes/nectar/",
    "colors": {
      "background": "#24272B",
      "foreground": "#C8CED5",
      "raised": "#2A2D32",
      "control": "#2A2D32",
      "border": "#3D424A",
      "accent": "#E5C07B",
      "mutedForeground": "#9AA1AA",
      "ring": "#E5C07B"
    }
  },
  {
    "id": "t3-nier-automata-light",
    "name": "NieR: Automata Light",
    "appearance": "light",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/nier-automata/",
    "colors": {
      "background": "#CCC8B1",
      "foreground": "#211F1B",
      "raised": "#D1CDB7",
      "control": "#C1BDA5",
      "border": "#A29E89",
      "accent": "#211F1B",
      "mutedForeground": "#4D4B3F",
      "ring": "#211F1B"
    }
  },
  {
    "id": "t3-nier-automata-dark",
    "name": "NieR: Automata Dark",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/nier-automata/",
    "colors": {
      "background": "#2F2D26",
      "foreground": "#D1CDB7",
      "raised": "#3B3930",
      "control": "#3D3B33",
      "border": "#4F4D45",
      "accent": "#D1CDB7",
      "mutedForeground": "#A8A593",
      "ring": "#D1CDB7"
    }
  },
  {
    "id": "t3-notion",
    "name": "Notion",
    "appearance": "dark",
    "author": "D3OXY",
    "source": "https://t3themes.com/themes/notion/",
    "colors": {
      "background": "#191919",
      "foreground": "#E6E6E6",
      "raised": "#252525",
      "control": "#252525",
      "border": "#373737",
      "accent": "#2383E2",
      "mutedForeground": "#9B9B9B",
      "ring": "#2383E2"
    }
  },
  {
    "id": "t3-one-dark-pro-night-flat-dark",
    "name": "One Dark Pro Night Flat Dark",
    "appearance": "dark",
    "author": "pantharshit007",
    "source": "https://t3themes.com/themes/one-dark-pro-night-flat/",
    "colors": {
      "background": "#16191D",
      "foreground": "#ABB2BF",
      "raised": "#23272E",
      "control": "#23272E",
      "border": "#3E4452",
      "accent": "#4D78CC",
      "mutedForeground": "#6C7482",
      "ring": "#4D78CC"
    }
  },
  {
    "id": "t3-one-dark-pro-night-flat-light",
    "name": "One Dark Pro Night Flat Light",
    "appearance": "light",
    "author": "pantharshit007",
    "source": "https://t3themes.com/themes/one-dark-pro-night-flat/",
    "colors": {
      "background": "#FAFAFA",
      "foreground": "#383A42",
      "raised": "#F0F0F1",
      "control": "#FFFFFF",
      "border": "#E5E5E6",
      "accent": "#4078F2",
      "mutedForeground": "#A0A1A7",
      "ring": "#4078F2"
    }
  },
  {
    "id": "t3-paper-ember-light",
    "name": "Paper Ember Light",
    "appearance": "light",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/paper-ember/",
    "colors": {
      "background": "#FAF6F0",
      "foreground": "#44403C",
      "raised": "#FDFAF5",
      "control": "#E0D5C5",
      "border": "#E7DDD0",
      "accent": "#C2571F",
      "mutedForeground": "#8A817A",
      "ring": "#C2571F"
    }
  },
  {
    "id": "t3-paper-ember-dark",
    "name": "Paper Ember Dark",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/paper-ember/",
    "colors": {
      "background": "#1C1917",
      "foreground": "#E7E5E4",
      "raised": "#2A2725",
      "control": "#3A3632",
      "border": "#33302C",
      "accent": "#EA884B",
      "mutedForeground": "#A8A29E",
      "ring": "#EA884B"
    }
  },
  {
    "id": "t3-phosphor",
    "name": "Phosphor",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/phosphor/",
    "colors": {
      "background": "#060B06",
      "foreground": "#A5EFB7",
      "raised": "#101C12",
      "control": "#122317",
      "border": "#1C3322",
      "accent": "#3DFF7C",
      "mutedForeground": "#549A67",
      "ring": "#3DFF7C"
    }
  },
  {
    "id": "t3-pierre-soft-light",
    "name": "Pierre Soft Light",
    "appearance": "light",
    "author": "one-om-jha",
    "source": "https://t3themes.com/themes/pierre-soft/",
    "colors": {
      "background": "#FFFFFF",
      "foreground": "#525252",
      "raised": "#F5F5F5",
      "control": "#E7F0F5",
      "border": "#EDEDED",
      "accent": "#009FFF",
      "mutedForeground": "#717476",
      "ring": "#009FFF"
    }
  },
  {
    "id": "t3-pierre-soft-dark",
    "name": "Pierre Soft Dark",
    "appearance": "dark",
    "author": "one-om-jha",
    "source": "https://t3themes.com/themes/pierre-soft/",
    "colors": {
      "background": "#171717",
      "foreground": "#D4D4D4",
      "raised": "#262626",
      "control": "#292D32",
      "border": "#1D1D1D",
      "accent": "#69B1FF",
      "mutedForeground": "#86898B",
      "ring": "#69B1FF"
    }
  },
  {
    "id": "t3-pierre-light",
    "name": "Pierre Light",
    "appearance": "light",
    "author": "one-om-jha",
    "source": "https://t3themes.com/themes/pierre/",
    "colors": {
      "background": "#FFFFFF",
      "foreground": "#0A0A0A",
      "raised": "#EDEDED",
      "control": "#E7F0F5",
      "border": "#E5E5E5",
      "accent": "#009FFF",
      "mutedForeground": "#717476",
      "ring": "#009FFF"
    }
  },
  {
    "id": "t3-pierre-dark",
    "name": "Pierre Dark",
    "appearance": "dark",
    "author": "one-om-jha",
    "source": "https://t3themes.com/themes/pierre/",
    "colors": {
      "background": "#0A0A0A",
      "foreground": "#FAFAFA",
      "raised": "#1D1D1D",
      "control": "#181F24",
      "border": "#0A0A0A",
      "accent": "#009FFF",
      "mutedForeground": "#7D8285",
      "ring": "#009FFF"
    }
  },
  {
    "id": "t3-purple-dark",
    "name": "Purple Dark",
    "appearance": "dark",
    "author": "vertopolkalf",
    "source": "https://t3themes.com/themes/purple-dark/",
    "colors": {
      "background": "#150E1D",
      "foreground": "#FFFFFF",
      "raised": "#291A39",
      "control": "#301F3A",
      "border": "#56406A",
      "accent": "#9E48D9",
      "mutedForeground": "#E9E7EC",
      "ring": "#9E48D9"
    }
  },
  {
    "id": "t3-rose-pine-dawn",
    "name": "Rosé Pine Dawn",
    "appearance": "light",
    "author": "Williawar",
    "source": "https://t3themes.com/themes/rose-pine-dawn/",
    "colors": {
      "background": "#FAF4ED",
      "foreground": "#27272A",
      "raised": "#FFFFFF33",
      "control": "#FFFFFF",
      "border": "#E8E2D9",
      "accent": "#286983",
      "mutedForeground": "#71717B",
      "ring": "#286983"
    }
  },
  {
    "id": "t3-sakura-light",
    "name": "Sakura Light",
    "appearance": "light",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/sakura/",
    "colors": {
      "background": "#FBF3F5",
      "foreground": "#432B36",
      "raised": "#FDF7F9",
      "control": "#F1DDE4",
      "border": "#ECD7DE",
      "accent": "#B83D72",
      "mutedForeground": "#8A6675",
      "ring": "#B83D72"
    }
  },
  {
    "id": "t3-sakura-dark",
    "name": "Sakura Dark",
    "appearance": "dark",
    "author": "SunkenInTime",
    "source": "https://t3themes.com/themes/sakura/",
    "colors": {
      "background": "#241820",
      "foreground": "#EEDBE4",
      "raised": "#33232F",
      "control": "#372531",
      "border": "#3C2A36",
      "accent": "#E88FB4",
      "mutedForeground": "#B18EA0",
      "ring": "#E88FB4"
    }
  },
  {
    "id": "t3-selenized-light",
    "name": "Selenized Light",
    "appearance": "light",
    "author": "chadhs",
    "source": "https://t3themes.com/themes/selenized/",
    "colors": {
      "background": "#FBF3DB",
      "foreground": "#53676D",
      "raised": "#FDFAF1",
      "control": "#ECE3CC",
      "border": "#CCC9B9",
      "accent": "#0072D4",
      "mutedForeground": "#79817E",
      "ring": "#0072D4"
    }
  },
  {
    "id": "t3-selenized-dark",
    "name": "Selenized Dark",
    "appearance": "dark",
    "author": "chadhs",
    "source": "https://t3themes.com/themes/selenized/",
    "colors": {
      "background": "#103C48",
      "foreground": "#ADBCBC",
      "raised": "#154450",
      "control": "#184956",
      "border": "#385F6A",
      "accent": "#4695F7",
      "mutedForeground": "#7C9197",
      "ring": "#4695F7"
    }
  },
  {
    "id": "t3-solarized-light",
    "name": "Solarized Light",
    "appearance": "light",
    "author": "chadhs",
    "source": "https://t3themes.com/themes/solarized/",
    "colors": {
      "background": "#FDF6E3",
      "foreground": "#657B83",
      "raised": "#FEFBF4",
      "control": "#FEFBF4",
      "border": "#CECFC3",
      "accent": "#268BD2",
      "mutedForeground": "#7A8282",
      "ring": "#268BD2"
    }
  },
  {
    "id": "t3-solarized-dark",
    "name": "Solarized Dark",
    "appearance": "dark",
    "author": "chadhs",
    "source": "https://t3themes.com/themes/solarized/",
    "colors": {
      "background": "#002B36",
      "foreground": "#839496",
      "raised": "#04323D",
      "control": "#062E38",
      "border": "#234A54",
      "accent": "#268BD2",
      "mutedForeground": "#727F86",
      "ring": "#268BD2"
    }
  },
  {
    "id": "t3-tokyo-night-dark",
    "name": "Tokyo Night Dark",
    "appearance": "dark",
    "author": "pantharshit007",
    "source": "https://t3themes.com/themes/tokyo-night/",
    "colors": {
      "background": "#1A1B26",
      "foreground": "#C0CAF5",
      "raised": "#1E202E",
      "control": "#202330",
      "border": "#292E42",
      "accent": "#7AA2F7",
      "mutedForeground": "#787C99",
      "ring": "#7AA2F7"
    }
  },
  {
    "id": "t3-tokyo-night-light",
    "name": "Tokyo Night Light",
    "appearance": "light",
    "author": "pantharshit007",
    "source": "https://t3themes.com/themes/tokyo-night/",
    "colors": {
      "background": "#E6E7ED",
      "foreground": "#343B59",
      "raised": "#E6E7ED",
      "control": "#E6E7ED",
      "border": "#C1C2C7",
      "accent": "#2959AA",
      "mutedForeground": "#707280",
      "ring": "#2959AA"
    }
  },
  {
    "id": "t3-vesper",
    "name": "Vesper",
    "appearance": "dark",
    "author": "PunGrumpy",
    "source": "https://t3themes.com/themes/vesper/",
    "colors": {
      "background": "#101010",
      "foreground": "#FFFFFF",
      "raised": "#161616",
      "control": "#1C1C1C",
      "border": "#1C1C1C",
      "accent": "#FFC799",
      "mutedForeground": "#A0A0A0",
      "ring": "#FFC799"
    }
  },
  {
    "id": "t3-vitesse-dark",
    "name": "Vitesse Dark",
    "appearance": "dark",
    "author": "MangMax",
    "source": "https://t3themes.com/themes/vitesse/",
    "colors": {
      "background": "#121212",
      "foreground": "#DBD7CAEE",
      "raised": "#1F1F1F",
      "control": "#181818",
      "border": "#191919",
      "accent": "#4D9375",
      "mutedForeground": "#959DA5",
      "ring": "#4D9375"
    }
  },
  {
    "id": "t3-vitesse-light",
    "name": "Vitesse Light",
    "appearance": "light",
    "author": "MangMax",
    "source": "https://t3themes.com/themes/vitesse/",
    "colors": {
      "background": "#FFFFFF",
      "foreground": "#393A34",
      "raised": "#FFFFFF",
      "control": "#F7F7F7",
      "border": "#F0F0F0",
      "accent": "#1C6B48",
      "mutedForeground": "#6A737D",
      "ring": "#1C6B48"
    }
  },
  {
    "id": "t3-whirl-dark",
    "name": "Whirl Dark",
    "appearance": "dark",
    "author": "saltjsx",
    "source": "https://t3themes.com/themes/whirl/",
    "colors": {
      "background": "#131313",
      "foreground": "#F0F0F0",
      "raised": "#252526",
      "control": "#232324",
      "border": "#2A2A2B",
      "accent": "#DEDEDE",
      "mutedForeground": "#888888",
      "ring": "#747474"
    }
  },
  {
    "id": "t3-whirl-light",
    "name": "Whirl Light",
    "appearance": "light",
    "author": "saltjsx",
    "source": "https://t3themes.com/themes/whirl/",
    "colors": {
      "background": "#F3F3F4",
      "foreground": "#141414",
      "raised": "#FFFFFF",
      "control": "#E9E9EB",
      "border": "#DCDCDD",
      "accent": "#0F0F0F",
      "mutedForeground": "#696969",
      "ring": "#808080"
    }
  },
  {
    "id": "t3-your-deepest-darkest-black",
    "name": "Your Deepest Darkest Black",
    "appearance": "dark",
    "author": "vkpdeveloper",
    "source": "https://t3themes.com/themes/your-deepest-darkest-black/",
    "colors": {
      "background": "#000000",
      "foreground": "#EDEDED",
      "raised": "#1F1F1F",
      "control": "#101010",
      "border": "#1F1F1F",
      "accent": "#62C073",
      "mutedForeground": "#A1A1A1",
      "ring": "#676767"
    }
  },
  {
    "id": "t3-zed-dark",
    "name": "Zed Dark",
    "appearance": "dark",
    "author": "Just-Bax",
    "source": "https://t3themes.com/themes/zed/",
    "colors": {
      "background": "#282C33",
      "foreground": "#DCE0E5",
      "raised": "#2F343E",
      "control": "#2F343E",
      "border": "#464B57",
      "accent": "#74ADE8",
      "mutedForeground": "#A9AFBC",
      "ring": "#74ADE8"
    }
  },
  {
    "id": "t3-zed-light",
    "name": "Zed Light",
    "appearance": "light",
    "author": "Just-Bax",
    "source": "https://t3themes.com/themes/zed/",
    "colors": {
      "background": "#FAFAFA",
      "foreground": "#242529",
      "raised": "#EBEBEC",
      "control": "#EBEBEC",
      "border": "#C9C9CA",
      "accent": "#5C78E2",
      "mutedForeground": "#58585A",
      "ring": "#5C78E2"
    }
  }
];
